#!/usr/bin/env python3
"""
Build the product-forward OG cards (STYLE_GUIDE §6.15.2).

Visits each page in headless Chromium, captures its hero visual as a PNG
(Playwright screenshot on the live DOM element — works on canvases too),
embeds that PNG as an <img> in a programmatically-injected OG frame, then
screenshots the frame at 2x device-scale and downsamples to 1280×720.

Cards produced (all written to the output directory, default = cwd):
    og-heatmap.jpg
    og-bitcoin-vs-the-stock-market.jpg
    og-the-bitcoin-retirement.jpg
    og-calculators.jpg

When to run
-----------
After each monthly Power Law / TODAY data refresh — the embedded chart
screenshots go stale otherwise. See MONTHLY_REFRESH_CHECKLIST.md §6.

The brand-forward family (§6.15.1 — Melting Ice Cube, Power Law, WMHTB,
etc.) does NOT need this script; those cards composite static atmospheric
artwork with no data dependency.

The homepage (og-image.jpg) was migrated from product-forward to
brand-forward on 2026-05-17 (commit 458a9fc041). It is intentionally not
regenerated by this script.

Usage
-----
    python3 scripts/build-og-images.py                  # writes to ./
    python3 scripts/build-og-images.py --output-dir og/ # writes to og/
    python3 scripts/build-og-images.py --only heatmap   # build one card

Or via the package.json shortcut:
    npm run build-ogs

Dependencies
------------
    pip install playwright pillow
    playwright install chromium

After regeneration
------------------
Verify each card serves from prod:
    curl -I https://lastcoinstanding.com/og-heatmap.jpg
must return `Content-Type: image/jpeg`. Then poke Facebook's debugger
(developers.facebook.com/tools/debug/) and post a draft tweet to force
re-scrape on the social platforms.
"""

import argparse
import base64
import io
import os
import sys
import time
from pathlib import Path

from PIL import Image
from playwright.sync_api import sync_playwright, TimeoutError as PWTimeout


# Editorial chrome injected into each page. The hero visual is passed as a
# data: URL so the page can <img src> it without a separate network round trip.
OG_INJECT_JS = r"""
async ({heroDataUrl, title, titleAccent, titleAfter, subtitle, statsHTML, urlText}) => {
    const old = document.getElementById('og-frame');
    if (old) old.remove();

    const frame = document.createElement('div');
    frame.id = 'og-frame';
    frame.style.cssText = `
        position: fixed;
        top: 0; left: 0;
        width: 1280px; height: 720px;
        z-index: 999999;
        background: linear-gradient(135deg, #0a0908 0%, #15130f 100%);
        font-family: 'Inter', -apple-system, system-ui, sans-serif;
        color: #f2eee8;
        display: flex;
        flex-direction: column;
        padding: 48px 64px;
        box-sizing: border-box;
        overflow: hidden;
    `;

    // Subtle amber-glow accent at top-right (matches §6.15.2 spec)
    const glow = document.createElement('div');
    glow.style.cssText = `
        position: absolute; inset: 0;
        background: radial-gradient(ellipse at top right, rgba(247, 147, 26, 0.07) 0%, transparent 55%);
        pointer-events: none;
    `;
    frame.appendChild(glow);

    // Header row: title (left) + brand mark (right)
    const header = document.createElement('div');
    header.style.cssText = `
        display: flex;
        justify-content: space-between;
        align-items: flex-start;
        position: relative;
        z-index: 1;
    `;

    const titleBlock = document.createElement('div');
    titleBlock.style.cssText = `max-width: 800px;`;
    titleBlock.innerHTML = `
        <h1 style="
            font-family: 'Cormorant Garamond', Georgia, serif;
            font-weight: 500;
            font-size: 56px;
            line-height: 1.05;
            margin: 0;
            color: #f2eee8;
            letter-spacing: -0.01em;
        ">${title}<em style="color: #F7931A; font-style: italic;">${titleAccent}</em>${titleAfter}</h1>
        <p style="
            font-family: 'Inter', sans-serif;
            font-weight: 400;
            font-size: 19px;
            line-height: 1.45;
            color: #c8c2b8;
            margin: 14px 0 0;
            max-width: 760px;
        ">${subtitle}</p>
    `;

    const brand = document.createElement('div');
    brand.style.cssText = `
        font-family: 'Inter', sans-serif;
        font-weight: 600;
        font-size: 12px;
        letter-spacing: 0.22em;
        color: rgba(255,255,255,0.55);
        text-transform: uppercase;
        padding-top: 8px;
        white-space: nowrap;
    `;
    brand.innerHTML = `<span style="color:#F7931A; margin-right:8px;">●</span>LAST COIN STANDING`;

    header.appendChild(titleBlock);
    header.appendChild(brand);

    // Hero slot — embeds the pre-captured screenshot as an <img>
    const heroSlot = document.createElement('div');
    heroSlot.style.cssText = `
        flex: 1;
        display: flex;
        align-items: center;
        justify-content: center;
        min-height: 0;
        position: relative;
        z-index: 1;
        margin-top: 12px;
        overflow: hidden;
    `;

    const heroImg = document.createElement('img');
    heroImg.style.cssText = `
        max-width: 100%;
        max-height: 100%;
        width: auto;
        height: auto;
        object-fit: contain;
        display: block;
    `;
    heroSlot.appendChild(heroImg);

    // Footer row: stats line (left) + URL (right)
    const footer = document.createElement('div');
    footer.style.cssText = `
        display: flex;
        justify-content: space-between;
        align-items: baseline;
        position: relative;
        z-index: 1;
        margin-top: 12px;
    `;

    const stats = document.createElement('div');
    stats.style.cssText = `
        font-family: 'Inter', sans-serif;
        font-weight: 400;
        font-size: 16.5px;
        color: #d6cfc3;
    `;
    stats.innerHTML = statsHTML;

    const url = document.createElement('div');
    url.style.cssText = `
        font-family: 'Inter', sans-serif;
        font-weight: 500;
        font-size: 13px;
        letter-spacing: 0.16em;
        text-transform: uppercase;
        color: rgba(255,255,255,0.5);
    `;
    url.textContent = urlText;

    footer.appendChild(stats);
    footer.appendChild(url);

    frame.appendChild(header);
    frame.appendChild(heroSlot);
    frame.appendChild(footer);

    document.body.appendChild(frame);

    // Wait for the hero image to finish loading and one paint frame.
    await new Promise((resolve, reject) => {
        heroImg.addEventListener('load', () => resolve());
        heroImg.addEventListener('error', () => reject(new Error('hero img failed to load')));
        heroImg.src = heroDataUrl;
    });
    await new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r)));
}
"""


# ---- Per-card configs ----
# Each card has:
#   name            — short id for --only filtering and progress logs
#   url             — live page to visit
#   hero_selector   — CSS selector for the element to screenshot
#   wait_after_navigate_ms — initial settle time after navigation
#   wait_after_scroll_ms   — wait after scrolling hero into view, lets
#                             intersection-observer-triggered renders finish
#                             (Chart.js animations, mini-tile renderers, etc.)
#   chrome.title           — text before the italic-amber accent
#   chrome.titleAccent     — the italic-amber word
#   chrome.titleAfter      — text after the italic-amber accent
#   chrome.subtitle        — one-sentence Inter subtitle
#   chrome.statsHTML       — bottom-left stats; <strong> renders amber bold
#   chrome.urlText         — bottom-right URL footer
#   output_filename        — written to args.output_dir / output_filename

CARDS = [
    {
        "name": "heatmap",
        "url": "https://lastcoinstanding.com/heatmap",
        "hero_selector": ".bvsm-heatmap-scroll-container",
        "wait_after_navigate_ms": 2500,
        "wait_after_scroll_ms": 0,
        "chrome": {
            "title": "The ",
            "titleAccent": "Bitcoin",
            "titleAfter": " Heatmap",
            "subtitle": "Bitcoin's outperformance vs. the S&P 500 — every monthly entry since 2010, every common holding horizon.",
            "statsHTML": (
                '<strong style="color:#F7931A; font-weight:700;">100% wins at 4y+ horizons</strong>'
                '  ·  <strong style="color:#F7931A; font-weight:700;">164.5×</strong>'
                ' average outperformance at 7-year horizons'
            ),
            "urlText": "lastcoinstanding.com/heatmap",
        },
        "output_filename": "og-heatmap.jpg",
    },
    {
        "name": "bvsm",
        "url": "https://lastcoinstanding.com/bitcoin-vs-the-stock-market",
        "hero_selector": "#bvsmCalcChart",
        "wait_after_navigate_ms": 1500,
        "wait_after_scroll_ms": 3500,
        "chrome": {
            "title": "",
            "titleAccent": "Bitcoin",
            "titleAfter": " vs. The Stock Market",
            "subtitle": "How $1,000 from 2010 grew under bitcoin, the S&P 500, and the NASDAQ-100 — the wealth-over-time stress test.",
            "statsHTML": (
                '<strong style="color:#F7931A; font-weight:700;">Bitcoin</strong>'
                '  ·  <strong style="color:#F7931A; font-weight:700;">S&amp;P 500 TR</strong>'
                '  ·  <strong style="color:#F7931A; font-weight:700;">NASDAQ-100 TR</strong>'
                '  ·  $1k from 2010 → today'
            ),
            "urlText": "lastcoinstanding.com/bitcoin-vs-the-stock-market",
        },
        "output_filename": "og-bitcoin-vs-the-stock-market.jpg",
    },
    {
        "name": "retirement",
        "url": "https://lastcoinstanding.com/the-bitcoin-retirement",
        "hero_selector": "#projectionChart",
        "wait_after_navigate_ms": 1500,
        "wait_after_scroll_ms": 3500,
        "chrome": {
            "title": "The ",
            "titleAccent": "Bitcoin",
            "titleAfter": " Retirement",
            "subtitle": "How does bitcoin support a retirement? Drag the sliders, watch the curves move, find your escape velocity.",
            "statsHTML": (
                '<strong style="color:#F7931A; font-weight:700;">Power Law projection</strong>'
                '  ·  portfolio value vs. traditional 60/40 across 50 years'
            ),
            "urlText": "lastcoinstanding.com/the-bitcoin-retirement",
        },
        "output_filename": "og-the-bitcoin-retirement.jpg",
    },
    {
        "name": "bvrp",
        "url": "https://lastcoinstanding.com/bitcoin-vs-rental-property#calculator",
        "hero_selector": "#calc-chart",
        "wait_after_navigate_ms": 2000,
        # Calculator tab needs to activate + chart needs to init lazily
        # (per STYLE_GUIDE §6.14 — chart defers to bvrp:tab-activated event).
        # The #calculator hash deep-link auto-activates the tab on load, but
        # give the Chart.js animation 4s to settle before screenshot.
        "wait_after_scroll_ms": 4000,
        "chrome": {
            "title": "Bitcoin vs. ",
            "titleAccent": "Rental Property",
            "titleAfter": "",
            "subtitle": "2\u00d7 the after-tax yield, no tenants, no maintenance, no policy risk \u2014 once landlord costs are surfaced honestly.",
            "statsHTML": (
                '<strong style="color:#F7931A; font-weight:700;">10\u201313% yield</strong>'
                '  \u00b7  ROC tax shield'
                '  \u00b7  Four operational paths'
                '  \u00b7  Power Law-anchored projection'
            ),
            "urlText": "lastcoinstanding.com/bitcoin-vs-rental-property",
        },
        "output_filename": "og-bitcoin-vs-rental-property.jpg",
    },
    {
        "name": "tools",
        "url": "https://lastcoinstanding.com/calculators",
        "hero_selector": ".calc-row-featured",
        "wait_after_navigate_ms": 1500,
        # Featured tiles use intersection observers + mini-renderer charts;
        # generous wait lets the previews paint before screenshot.
        "wait_after_scroll_ms": 4000,
        "chrome": {
            "title": "",
            "titleAccent": "Tools",
            "titleAfter": "",
            "subtitle": "A working gallery of interactive tools to think through bitcoin decisions in your own life — past, present, and future.",
            "statsHTML": (
                '<strong style="color:#F7931A; font-weight:700;">12 tools</strong>'
                '  ·  heatmaps, projections, rebalancing strategies, retirement math'
            ),
            "urlText": "lastcoinstanding.com/calculators",
        },
        "output_filename": "og-calculators.jpg",
    },
    {
        "name": "power-law",
        "url": "https://lastcoinstanding.com/the-power-law",
        "hero_selector": "#powerLawChart",
        "wait_after_navigate_ms": 1500,
        "wait_after_scroll_ms": 3500,
        "chrome": {
            "title": "Bitcoin & The ",
            "titleAccent": "Power",
            "titleAfter": " Law",
            "subtitle": "Bitcoin's price has tracked a single growth equation across nine orders of magnitude since 2010 — the structural model behind the long-duration thesis.",
            "statsHTML": (
                '<strong style="color:#F7931A; font-weight:700;">Trend doubles every 13% increase in bitcoin&rsquo;s age</strong>'
                '  ·  floor 0.42&times;  ·  ceiling 3&times;'
            ),
            "urlText": "lastcoinstanding.com/the-power-law",
        },
        "output_filename": "og-the-power-law.jpg",
    },
    {
        "name": "bvre",
        "url": "https://lastcoinstanding.com/bitcoin-vs-real-estate",
        "hero_selector": "#eraBarChart",
        # eraBarChart sits inside the "Affordability Crisis" tab (Tab IV), not
        # the default. Click that tab first to make the panel visible.
        "click_before_capture": "button.tab-btn[data-tab='crisis']",
        "wait_after_navigate_ms": 1500,
        "wait_after_scroll_ms": 3500,
        "chrome": {
            "title": "",
            "titleAccent": "Bitcoin",
            "titleAfter": " vs. Real Estate",
            "subtitle": "135 years of US housing affordability — and what changed when the dollar&rsquo;s monetary regime did. Homes priced in real money tell a different story.",
            "statsHTML": (
                '<strong style="color:#F7931A; font-weight:700;">1890–2025</strong>'
                '  ·  home-price-to-income across five monetary eras'
            ),
            "urlText": "lastcoinstanding.com/bitcoin-vs-real-estate",
        },
        "output_filename": "og-bitcoin-vs-real-estate.jpg",
    },
    {
        "name": "lob",
        "url": "https://lastcoinstanding.com/living-on-bitcoin",
        "hero_selector": "#lobChart",
        # lobChart sits inside the "Calculator" tab (Tab III), not the default.
        # Click that tab first to make the panel visible.
        "click_before_capture": "button.tab-btn[data-tab='calculator']",
        "wait_after_navigate_ms": 1500,
        "wait_after_scroll_ms": 3500,
        "chrome": {
            "title": "Living on ",
            "titleAccent": "Bitcoin",
            "titleAfter": "",
            "subtitle": "Holding operating cash in bitcoin and paying fiat bills as they come due — modest economics, real friction, and the psychological payoff.",
            "statsHTML": (
                '<strong style="color:#F7931A; font-weight:700;">Power Law projection</strong>'
                '  ·  BTC float vs. USD float  ·  drawdown stress test'
            ),
            "urlText": "lastcoinstanding.com/living-on-bitcoin",
        },
        "output_filename": "og-living-on-bitcoin.jpg",
    },
    {
        "name": "bbm",
        "url": "https://lastcoinstanding.com/bitcoin-backed-mortgages",
        "hero_selector": "#bbmWealthChart",
        "wait_after_navigate_ms": 1500,
        "wait_after_scroll_ms": 3500,
        "chrome": {
            "title": "Bitcoin-Backed ",
            "titleAccent": "Mortgages",
            "titleAfter": "",
            "subtitle": "Pledge bitcoin instead of selling it to fund a home down-payment — Fannie-Mae-conforming, no margin call, and when it may make sense.",
            "statsHTML": (
                '<strong style="color:#F7931A; font-weight:700;">Pledge vs. Sell</strong>'
                '  ·  cumulative cost over time  ·  crossover marked'
            ),
            "urlText": "lastcoinstanding.com/bitcoin-backed-mortgages",
        },
        "output_filename": "og-bitcoin-backed-mortgages.jpg",
    },
    {
        "name": "the-gallery",
        "url": "https://lastcoinstanding.com/the-gallery",
        "hero_selector": "#galleryChannelChart",
        "wait_after_navigate_ms": 1800,
        "wait_after_scroll_ms": 3500,
        "chrome": {
            "title": "The ",
            "titleAccent": "Gallery",
            "titleAfter": "",
            "subtitle": "A vertical scroll-through of the ten most striking charts across Last Coin Standing — each chart full-size, with editorial framing.",
            "statsHTML": (
                '<strong style="color:#F7931A; font-weight:700;">10 charts</strong>'
                '  ·  Power Law, housing, retirement, heatmap, horizons'
                '  ·  the case in one scroll'
            ),
            "urlText": "lastcoinstanding.com/the-gallery",
        },
        "output_filename": "og-the-gallery.jpg",
    },
]


def capture_hero_png(page, selector: str, wait_after_scroll_ms: int = 0) -> bytes:
    """Take a Playwright screenshot of a DOM element, return PNG bytes.
    Scrolls into view first; optional post-scroll wait lets intersection-
    observer-triggered renders (Chart.js, mini-tiles) finish painting.
    """
    el = page.locator(selector)
    el.scroll_into_view_if_needed()
    if wait_after_scroll_ms:
        page.wait_for_timeout(wait_after_scroll_ms)
    return el.screenshot(type="png")


def png_to_data_url(png_bytes: bytes) -> str:
    return "data:image/png;base64," + base64.b64encode(png_bytes).decode()


def build_card(page, card_config: dict, output_path: Path) -> None:
    """Build one OG card. Writes JPEG to output_path."""
    started = time.time()
    print(f"  visit {card_config['url']}")
    page.goto(card_config["url"], wait_until="networkidle")
    try:
        page.wait_for_selector(
            card_config["hero_selector"], state="attached", timeout=10_000)
    except PWTimeout:
        raise RuntimeError(
            f"hero selector not found on page: {card_config['hero_selector']}")
    page.wait_for_timeout(card_config["wait_after_navigate_ms"])

    # Optional: click an element before capture (e.g. a tab button to reveal
    # the hero chart on a tabbed page). The chart panel must become visible
    # before scroll_into_view_if_needed will succeed.
    click_selector = card_config.get("click_before_capture")
    if click_selector:
        print(f"  click {click_selector}")
        page.click(click_selector)
        page.wait_for_timeout(900)  # tab transition + chart render

    # 1. Capture hero element as a PNG
    hero_png = capture_hero_png(
        page,
        card_config["hero_selector"],
        wait_after_scroll_ms=card_config.get("wait_after_scroll_ms", 0),
    )
    print(f"  hero PNG: {len(hero_png):,} bytes")
    hero_data_url = png_to_data_url(hero_png)

    # 2. Inject OG frame with the hero embedded as <img>
    chrome = dict(card_config["chrome"])
    chrome["heroDataUrl"] = hero_data_url
    page.evaluate(OG_INJECT_JS, chrome)
    page.wait_for_timeout(300)

    # 3. Screenshot the frame (2x device-scale gives 2560x1440)
    frame = page.locator("#og-frame")
    png_bytes = frame.screenshot(type="png")

    # 4. Downsample → 1280x720 and save as JPEG quality 82
    img = Image.open(io.BytesIO(png_bytes))
    if img.size != (1280, 720):
        img = img.resize((1280, 720), Image.LANCZOS)
    img = img.convert("RGB")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    img.save(output_path, "JPEG", quality=82, optimize=True, progressive=False)
    elapsed = time.time() - started
    print(f"  wrote {output_path} ({output_path.stat().st_size:,} bytes, "
          f"{elapsed:.1f}s)")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument(
        "--output-dir", default=".",
        help="Directory to write the JPEG files into (default: current directory)")
    ap.add_argument(
        "--only", action="append", choices=[c["name"] for c in CARDS],
        help="Build only the named card (can be passed multiple times)")
    args = ap.parse_args()

    output_dir = Path(args.output_dir).resolve()
    cards = CARDS if not args.only else [c for c in CARDS if c["name"] in args.only]

    print(f"Building {len(cards)} card(s) to {output_dir}")

    failures = []
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.new_context(
            viewport={"width": 1280, "height": 900},
            device_scale_factor=2,
        )
        page = context.new_page()

        for cfg in cards:
            print(f"\n[{cfg['name']}] {cfg['output_filename']}")
            try:
                build_card(page, cfg, output_dir / cfg["output_filename"])
            except Exception as e:
                print(f"  FAILED: {type(e).__name__}: {e}")
                failures.append((cfg["name"], str(e)))

        browser.close()

    if failures:
        print(f"\n{len(failures)} card(s) failed:")
        for name, err in failures:
            print(f"  {name}: {err}")
        return 1
    print(f"\nAll {len(cards)} card(s) built successfully.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
